version: '3.7'

services:

  nextjs:
    container_name: nextjs
    build:
      context: './nextjs_app'
      dockerfile: Dockerfile
    volumes:
      - './nextjs_app:/app'
      - '/app/node_modules'
    depends_on:
      - strapi
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  strapi:
    container_name: strapi
    build:
      context: './strapi_cms'
      dockerfile: Dockerfile
    volumes:
      - './strapi_cms:/srv/app'
      - '/srv/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    container_name: nginx 
    build:
      context: './nginx'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - strapi
      - nextjs
    environment:
      - CHOKIDAR_USEPOLLING=true
