version: '3.7'

services:

  nextjs_personal_site:
    container_name: nextjs_personal_site
    build:
      context: './nextjs_app'
      dockerfile: Dockerfile
    volumes:
      - './nextjs_app:/app'
      - '/app/node_modules'
    depends_on:
      - strapi_personal_site
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  strapi_personal_site:
    container_name: strapi_personal_site
    build:
      context: './strapi_cms'
      dockerfile: Dockerfile
    volumes:
      - './strapi_cms:/srv/app'
      - '/srv/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx_personal_site:
    container_name: nginx_personal_site 
    build:
      context: './nginx'
      dockerfile: 'Dockerfile'
    ports:
      - '80:80'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - strapi_personal_site
      - nextjs_personal_site
    environment:
      - CHOKIDAR_USEPOLLING=true
