# Base on offical Node.js Alpine image
FROM node:alpine

# Set working directory
WORKDIR /app

COPY ./package.json ./

# Install dependencies
RUN yarn install --production=true

# Copy all files
COPY ./ ./

# Build app
RUN yarn build

# Expose the listening port
EXPOSE 3000

# Run npm start script when container starts
CMD [ "yarn", "start" ]
