name: Create and push Docker images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make nextjs .env.local
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_URL: ${{ secrets.API_URL }}
          file_name: ./nextjs_app/.env.local
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build
        run: |
          docker build -f ./strapi_cms/Dockerfile.prod ./strapi_cms -t personal_website_strapi
      - name: docker build next.js
        run: |
          docker build -f ./nextjs_app/Dockerfile.prod ./nextjs_app -t personal_website_nextjs
      - name: docker build nginx
        run: |
          docker build -f ./nginx/Dockerfile.prod ./nginx -t personal_website_nginx
      - name: docker push
        run: |
          docker push personal_website_strapi
          docker push personal_website_nextjs
          docker push personal_website_nginx
