name: Create and push Docker images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make nextjs .env.local
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_URL: ${{ secrets.API_URL }}
          file_name: ./nextjs_app/.env.local

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker-compose build
        run: |
          docker-compose -f docker-compose.prod.yml up --build -d

      - name: Stop containers
        if: always()
        run: docker-compose down

      - name: docker push
        run: |
          docker push eilifakerjordet/strapi_personal_site:1.0.0
          docker push eilifakerjordet/nextjs_personal_site:1.0.0
          docker push eilifakerjordet/nginx_personal_site:1.0.0
